/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RunId = IDL.Nat;
export const WeatherResult = IDL.Record({
  'temperature' : IDL.Float64,
  'humidity' : IDL.Int,
});
export const Timestamp = IDL.Int;
export const GpxPoint = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
  'timestamp' : Timestamp,
});
export const Run = IDL.Record({
  'id' : RunId,
  'startTime' : Timestamp,
  'maxSpeedMps' : IDL.Float64,
  'endTime' : Timestamp,
  'avgPaceSecsPerKm' : IDL.Float64,
  'totalDistanceMeters' : IDL.Float64,
  'gpxPoints' : IDL.Vec(GpxPoint),
  'durationSeconds' : IDL.Int,
});
export const RunInput = IDL.Record({
  'startTime' : Timestamp,
  'maxSpeedMps' : IDL.Float64,
  'endTime' : Timestamp,
  'avgPaceSecsPerKm' : IDL.Float64,
  'totalDistanceMeters' : IDL.Float64,
  'gpxPoints' : IDL.Vec(GpxPoint),
  'durationSeconds' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'deleteRun' : IDL.Func([RunId], [IDL.Bool], []),
  'fetchWeather' : IDL.Func([IDL.Float64, IDL.Float64], [WeatherResult], []),
  'getAllRuns' : IDL.Func([], [IDL.Vec(Run)], ['query']),
  'getRunById' : IDL.Func([RunId], [IDL.Opt(Run)], ['query']),
  'saveRun' : IDL.Func([RunInput], [Run], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RunId = IDL.Nat;
  const WeatherResult = IDL.Record({
    'temperature' : IDL.Float64,
    'humidity' : IDL.Int,
  });
  const Timestamp = IDL.Int;
  const GpxPoint = IDL.Record({
    'lat' : IDL.Float64,
    'lon' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  const Run = IDL.Record({
    'id' : RunId,
    'startTime' : Timestamp,
    'maxSpeedMps' : IDL.Float64,
    'endTime' : Timestamp,
    'avgPaceSecsPerKm' : IDL.Float64,
    'totalDistanceMeters' : IDL.Float64,
    'gpxPoints' : IDL.Vec(GpxPoint),
    'durationSeconds' : IDL.Int,
  });
  const RunInput = IDL.Record({
    'startTime' : Timestamp,
    'maxSpeedMps' : IDL.Float64,
    'endTime' : Timestamp,
    'avgPaceSecsPerKm' : IDL.Float64,
    'totalDistanceMeters' : IDL.Float64,
    'gpxPoints' : IDL.Vec(GpxPoint),
    'durationSeconds' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'deleteRun' : IDL.Func([RunId], [IDL.Bool], []),
    'fetchWeather' : IDL.Func([IDL.Float64, IDL.Float64], [WeatherResult], []),
    'getAllRuns' : IDL.Func([], [IDL.Vec(Run)], ['query']),
    'getRunById' : IDL.Func([RunId], [IDL.Opt(Run)], ['query']),
    'saveRun' : IDL.Func([RunInput], [Run], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };