/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GpxPoint {
  'lat' : number,
  'lon' : number,
  'timestamp' : Timestamp,
}
export interface Run {
  'id' : RunId,
  'startTime' : Timestamp,
  'maxSpeedMps' : number,
  'endTime' : Timestamp,
  'avgPaceSecsPerKm' : number,
  'totalDistanceMeters' : number,
  'gpxPoints' : Array<GpxPoint>,
  'durationSeconds' : bigint,
}
export type RunId = bigint;
export interface RunInput {
  'startTime' : Timestamp,
  'maxSpeedMps' : number,
  'endTime' : Timestamp,
  'avgPaceSecsPerKm' : number,
  'totalDistanceMeters' : number,
  'gpxPoints' : Array<GpxPoint>,
  'durationSeconds' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface WeatherResult { 'temperature' : number, 'humidity' : bigint }
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'deleteRun' : ActorMethod<[RunId], boolean>,
  'fetchWeather' : ActorMethod<[number, number], WeatherResult>,
  'getAllRuns' : ActorMethod<[], Array<Run>>,
  'getRunById' : ActorMethod<[RunId], [] | [Run]>,
  'saveRun' : ActorMethod<[RunInput], Run>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];